### ISSUE TITLE
Document the magnitude endpoint

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/hydra-web-service#19]
Should be in "magnitude.html". Potentially mimic formatting in usgs/hazdev-geoserve-ws

**Comment by emartinez-usgs** [comment]
- The first sentence is unclear `...detailed magnitude information for a specific Hydra given a Hydra Universal ID (HUID)...` am I just unclear on Hyrda ontology?
- Example URL should include protocol and host information. You can generate this based on configuration parameters.
- Actual endpoint parameter names are `author`, `installation`, and `magtype`.
- Might more than one magnitude be returned?
- The response is a JSON object with `data`, `error` and `metadata` keys. The `response.data` is a GeoJSON Feature Object.
- The geometry is not optional property, but that property value may be null.
- The geometry is a GeoJSON Point Object. Coordinates are latitude, longitude, _depth_ (not elevation).
- It is not clear to me what the "Hydra/Magnitude" and "Hydra/Magnitude/MomentTensor" headers are delineating.
- When describing the output, give an example and link the keys to a "glossary" page that describes the value. Description lists `<dl><dt></dt><dd></dd></dl>` work great for this. Similar to what is done for the [fdsnws](http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson_detail.php).
- The `is-inteneral` variable is documented twice.
- Fix up validation errors.
   - Consider https://validator.w3.org/ You can use direct input.
   - At a minimum, fix errors. Most warnings would be addressed with more semantic markup.

**Comment by jpatton-USGS** [comment]
Is there an example on how to make a URL that includes protocol and host information?

**Comment by jmfee-usgs** [comment]
http://stackoverflow.com/questions/10183291/how-to-get-the-full-url-in-express?answertab=votes#tab-top

It would also be useful to add a `url` property for a given magnitude summary output by the event end point.
