### ISSUE TITLE
Data Factory

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/hydra-web-service#6]
accept a database connection

2 methods 

getEventSummary(HUID) :: return eventSummary model

getMagnitudeDetails(HUID, MagType, Installation, Author) :: return magnitude details model object

**Comment by jmfee-usgs** [comment]
# Event Summary

view all_events_info

eventtime => torigin (decimal seconds)
latitude => dlat (degrees)
longitude => dlon (degrees)
depth => ddepth (km)
id => huidevent
magnitude => dprefmag
magnitude type => imagtype (look up enumerated)
title => sregion

latitude error
longitude error
depth error

enumerated event types in TBD table
enumerated magnitude types in "magtype" table


view all_mags_for_event_info_wc

KEY:
value => dmagavg
magnitude type => imagtype
installation => sinstcode
author => sname

author name => snamehr

**Comment by jmfee-usgs** [comment]
# Magnitude Detail

value => 
magnitude type
installation
author

num obs used
num obs total
isInternal
isPreferredForType
isPublishable
associated by
comment

moment
derived time
derived location
derived depth
method
fit
variance reduction
percent dc
tensor params
nodal planes
percent clvd (1 - percentdc)

source time function
input source
azimuthal gap
condition number

**Comment by jmfee-usgs** [comment]
Created as part of #1 and #2
